# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'RandoMice' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for BGrain
    pod 'Kingfisher', '~> 4.6.2'
    pod 'KYDrawerController', '~> 2.0.4'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Toast-Swift', '~> 3.0.1'
end
